### ISSUE TITLE
Default sorting map list

### ISSUE THREAD

**Issue by johannes69** [johnpitchers/FocalPoint-Maps-for-Joomla#1]
Hi it took me a long time to figure out what the default sorting of the map list is and I noticed that its sorted by the last time a location was saved. Any chance it can sort alphabetically?

**Comment by thubamamba** [comment]
Did you ever get a solution for this? I am having the same problem.

**Comment by johnpitchers** [comment]
There is no built in sorting for the map list in this version of FocalPoint. However, the project has been taken over by Joomlashack who now develop it in-house under the name Shack Locations. https://www.joomlashack.com/joomla-extensions/shack-locations/
